name: Static Analysis

on:
  push:
    branches:
      - 'master'
  pull_request:

jobs:
  static-analysis:
    name: 'Lint and Type-check'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Install dependencies
        uses: bahmutov/npm-install@v1
      - name: Type Check
        run: yarn typecheck
      - name: Lint
        run: yarn lint
