name: Unit Test

on:
  push:
    branches:
      - 'master'
  pull_request:

jobs:
  matrix:
    name: 'Node ${{ matrix.node }}'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [14, 16]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - name: Install dependencies
        uses: bahmutov/npm-install@v1
      - name: Unit Test
        run: yarn test

